###
POST http://localhost:5000/api/v2/series HTTP/1.1
Content-Type: application/json

{
  "serie": "Peaky Blinder",
  "number_seasons": 4,
  "original_lenguage": "English",
  "features_seasons": {
    "season_number": 1,
    "season_name": "New season",
    "premier_date": "2022-11-23",
    "cast": ["Robert", "Arthur"],
    "episodes": {
      "episode_name": "Un nuevo misterio",
      "time_duration": 30
    }
  }
}


###
GET http://localhost:5000/api/v2/series HTTP/1.1

###
GET http://localhost:5000/api/v2/series/6241fd837fa233137cd33cf5 HTTP/1.1


###
GET http://localhost:5000/api/v2/series/actors/Arthur

###
GET http://localhost:5000/api/v2/series/premier/2022-11-23

###
PUT http://localhost:5000/api/v2/series/62420c743b8e9c0c6ef4a3e0 HTTP/1.1
Content-Type: application/json

{
  "serie": "Sherlock",
  "number_seasons": 3,
  "original_lenguage": "English (GB)",
  "features_seasons": {
    "season_number": 1,
    "season_name": "Mistery",
    "premier_date": "2022-10-23",
    "cast": ["Sergio", "Armando"],
    "episodes": {
      "episode_name": "Un nuevo misterio",
      "time_duration": 30
    }
  }
}

###
DELETE http://localhost:5000/api/v2/series/6241fea2796bf9d85c721370 HTTP/1.1
